### ISSUE TITLE
One page per source file: How to do circular links

### ISSUE THREAD

**Issue by FrigoEU** [urweb/urweb#118]
This is a question, not an issue but I haven't had much luck getting answers on IRC so I'll ask it here. It feels intuitive to me to have different pages in different files, let's say page A in a.ur, and page B in b.ur. Is it then possible to link from page A to page B AND from page B to page A using the "link" property of an "a" tag? Right now I'm side stepping this by using actual string urls, but it's less safe + you have to add each one in your .urp file...

**Comment by achlipala** [comment]
Unfortunately, Ur/Web inherits from the ML family lack of direct mutual recursion across modules.  (It's not obvious as an "unfortunately," actually, because it's hard to see how to keep the semantics as nice while allowing cross-module recursion.)

You can achieve a similar effect by making one of the two pages higher-order, taking the function for the other as an argument.  The Ur/Web compiler specializes all server-side higher-order functions at compile time, so no code-passing will be left in the running server.

**Comment by FrigoEU** [comment]
Great, that's a good idea! I'll definitely be using that. Thanks a lot!

**Comment by ashalkhakov** [comment]
You may also pass terms of type `url` directly to wherever you want (and the function of same name will help you construct terms of this type).
