### ISSUE TITLE
CUnify exception when using pairs

### ISSUE THREAD

**Issue by proger** [urweb/urweb#125]
Minimum reproducible script, works on both 20170720 and master e1ae0ce918c234cbb0b5a6ee72e0443bd04d4127:

```ur
datatype a = A
datatype b = B

val x : (a * b) = (A, B)

val y : b = x
```

```console
% urweb -tc -timing -dumpSource demo
unhandled exception: CUnify
```

I also wonder if there's any nice way beyond grep to get more information about this exception to start looking for causes, it would also be nice for `timing`/`dumpSource` to work in such cases, could you tell if this is a lot of work from the top of your head?

**Comment by achlipala** [comment]
Thanks for the report.  I'll look into it soon.

I've never invested much in special compiler-debugging support, and I especially haven't worked on documenting that support, since I tend to tackle all the fixes myself.  But the most basic shift here is to run the compiler inside the SML/NJ toplevel, where there is indeed more information on exceptions.

**Comment by achlipala** [comment]
Should be fixed now.  I'm surprised that one went so long without getting noticed!

**Comment by proger** [comment]
Thank you!
