### ISSUE TITLE
Unexpected compilation error: Anonymous function remains at code generation

### ISSUE THREAD

**Issue by fabriceleal** [urweb/urweb#144]
I seem to have an issue trying to compile a project that uses an anonymous function in an algebraic data type; the issue is happening in this project (please mind the branch):

 https://github.com/fabriceleal/urweb-nregex/blob/master3/nregex.ur

However, I was trying to replicate this behavior but i'm **unable** to with this test:

```urweb

fun testFn c = isdigit c

datatype t =
	 Test of (char -> bool)
       | Ok
       | Test2 of (char -> bool) * (char -> bool)
       | Test3 of (char -> bool) * (char -> bool)

fun test v c =
    case v of
	Test f => f c
      | Ok => True
      | Test2 (f1, f2) => (f1 c) && (f2 c) 
      | Test3 (f1, f2) => (f1 c) || (f2 c)

fun index () =
    return <xml>
      <body>
	{[(show (test (Test3 (testFn, isalpha)) #"c"))]}
      </body>
    </xml>
```

**Comment by fabriceleal** [comment]
I see. Maybe I can "cheat" and instead of providing a char -> bool I can provide some other algebraic data type to "symbolize" char sets (alphanum, digit, etc) and make a single function that tests if a char "belongs" to that set of characters? I'll try it after dinner. For now I've been providing lists of chars but now I'm starting to feel hindered.

**Comment by fabriceleal** [comment]
It seems to work! I assume there's no first class functions on the server side because it's being compiled to C?

**Comment by achlipala** [comment]
I'm glad that you solved your particular issue.  Yes, your prose description of a workaround sounds reasonable.

And you're also right that, basically, the server-side compilation strategy doesn't include an explicit implementation of closures, and the target language C doesn't support them natively, so they have just never been allowed.  It would not be too hard to add support for first-class functions on the server side, but I kind of like being forced to avoid them, since I think they are way overused in code today.  I appreciate having help from the compiler in avoiding the runtime overhead of building closures or passing them around!
