### ISSUE TITLE
meta tag misses attributes

### ISSUE THREAD

**Issue by robinp** [urweb/urweb#167]
Namely the non-obsolete attribs `charset` and `http-equiv` are not supported, see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta.

I use a local definition such as:
```
val meta : unit -> tag [
      Nam = meta, Content = string, Id = id,
      Charset = string, Http_equiv = string] head [] [] []
```

**Comment by achlipala** [comment]
It was an intentional decision to omit `http-equiv`, since the ability to set arbitrary HTTP headers is quite scary from a security perspective.  Currently headers are whitelisted via `allow requestHeader` in `.urp` files, so we could conceivably use the same whitelist to control what can go into `<meta>` tags, but I find it unsettling if inert pieces of HTML syntax (coming e.g. from library functions) can have such broad consequences for the behavior of applications.

So far, I haven't seen a compelling case for exposing `<meta charset`, since it has seemed nicer for Ur/Web to force UTF-8 universally, which is currently done by setting HTTP headers rather than within HTML documents.  I'm quite open to PRs that "fix" the Ur/Web implementation to change how applications tell the world that they use UTF-8, and I'm less convinced that we want to make it all configurable, especially through freeform HTML tags (rather than, say, new `.urp` directives).

**Comment by robinp** [comment]
As for `http-equiv`, `bootstrap4` suggested using it for `<meta http-equiv="X-UA-Compatible" content="IE=edge">`, which honestly sounds like something I wouldn't like resources poured into for support.

Agree about charset. mozdev writes it is obsolete in favor of http-equiv with Content-Type, but that is not needed if the header is set anyway.

Thanks for the clarifying comment! Closing now, if anyone with the need discovers now knows which direction to try.
