### ISSUE TITLE
File/location info with -dumpTypes switch

### ISSUE THREAD

**Issue by ashalkhakov** [urweb/urweb#169]
Here's a feature request. We have the `-dumpTypes` switch, but it's not as useful as it could be.

1. output file and location for every binding
2. use a format that would be easily parsed by third parties (e.g. JSON or S-expressions)

We can then easily plug this into an editor (use case: find the type of expression under cursor).

I think this feature was mentioned in the mailing list a while back.

**Comment by achlipala** [comment]
I'd certainly be open to a PR providing this enhancement.

**Comment by ashalkhakov** [comment]
I currently have something like this:

```json
{"type": "structure",
 "id": "Case",
 "loc": {"source": "case.ur","start": {"line": 0,"col": 0},"end": {"line": 0,"col": 0}},
 "body": [
 {"type": "val",
 "id": "swap",
 "loc": {"source": "case.ur","start": {"line": 3,"col": 0},"end": {"line": 5,"col": 0}},
 "annotation": "t -> t"
 },
 {"type": "val",
 "id": "out",
 "loc": {"source": "case.ur","start": {"line": 7,"col": 0},"end": {"line": 9,"col": 0}},
 "annotation": "u -> t"
 },
 {"type": "val",
 "id": "is_two",
 "loc": {"source": "case.ur","start": {"line": 11,"col": 0},"end": {"line": 14,"col": 0}},
 "annotation": "nat -> t"
 },
 {"type": "val",
 "id": "shw",
 "loc": {"source": "case.ur","start": {"line": 14,"col": 0},"end": {"line": 17,"col": 0}},
 "annotation": "t -> string"
 },
 {"type": "val",
 "id": "main",
 "loc": {"source": "case.ur","start": {"line": 17,"col": 0},"end": {"line": 32,"col": 13}},
 "type": "{} -> transaction (xml ([Html = ()]) ([]) ([]))"
 },
 ]
 }
```

It has some minor issues (e.g. the trailing comma in the list is invalid JSON and the position info on the module itself is wrong). I'm wondering if anybody has ideas about this format. Is it OK? See also the [branch](https://github.com/ashalkhakov/urweb/tree/dumpTypesLocations)

**Comment by achlipala** [comment]
Glad to see more progress on this enhancement!  I don't have any personal uses for the feature in mind, so I'm not a good source of feedback.  Perhaps the question is even worth taking to the mailing list.

**Comment by FrigoEU** [comment]
Looks OK to me. I have some experience with PureScript developer tooling and this is the JSON structure that they use to communicate identifier type information:

```
[
  {
  "module": "Data.Array",
  "identifier": "filter",
  "type": "forall a. (a -> Boolean) -> Array a -> Array a",
  "expandedType": "forall a. (a -> Boolean) -> Array a -> Array a",
  "definedAt":
    {
    "name": "/path/to/file",
    "start": [1, 3],
    "end": [3, 1]
    },
  "documentation": "A filtering function",
  "exportedFrom": ["Data.Array"]
  }
]
````

[psc-ide protocol](https://github.com/purescript/purescript/blob/master/psc-ide/PROTOCOL.md)

**Comment by ashalkhakov** [comment]
I took a look at PureScript tooling and it merits another, closer look. They eschewed the Language Server Protocol implementation, opting instead for a simpler server, and for a good reason. This needs more thought (since the next thing after this would be editor integration!).

**Comment by FrigoEU** [comment]
Hey @ashalkhakov, have you done any work on this? My product work is slowing down a little bit now and I'd like to get some work in on some essential tooling. I'm mostly interested in type-under-cursor and autocompletion.

An issue I see with using -dumpTypes is that local bindings are not included.  I feel these local bindings (let-bindings & function parameters mostly) are maybe even more valuable to find automatically since top-level bindings I mostly have in .urs files with explicit type annotations anyway. 

I've only just started looking at the implementation of the elaboration and the daemon, but it would be great if we could use the daemon to quickly get this local information, either through caching or ad-hoc reparsing & re-elaborating the current context (say the current top-level function). Is that something that is already in the daemon? 

In terms of autocompletion it would be great if we could use the same machinery to also get context-sensitive autocompletion (so including local bindings). Parse errors might be a problem here, I'm not sure how other languages handle this...

About LSP protocol vs having your own (like PureScript): I feel starting with a proprietary way of getting the information out of the compiler is the start. Implementing the actual protocol itself, possibly by adding a translation layer, is always possible and not really a priority atm (since there is nothing right now :D).

Anyway a bit of a braindump here, but I'd just like to see where you're at in this project, how we could get local bindings in, and if we could use the daemon or if that is just a bad way to go.

Simon

**Comment by ashalkhakov** [comment]
Hi @FrigoEU, unfortunately I [stopped](https://github.com/ashalkhakov/urweb/tree/dumpTypesLocations) working on it for now due to lack of time. Feel free to use the code I wrote there.

I'll address your points now:

> An issue I see with using -dumpTypes is that local bindings are not included. I feel these local bindings (let-bindings & function parameters mostly) are maybe even more valuable to find automatically since top-level bindings I mostly have in .urs files with explicit type annotations anyway.

Good point, but I'm not sure how you'd express scoping in JSON output? Any ideas?

> I've only just started looking at the implementation of the elaboration and the daemon, but it would be great if we could use the daemon to quickly get this local information, either through caching or ad-hoc reparsing & re-elaborating the current context (say the current top-level function). Is that something that is already in the daemon?

I think the reparsing and re-elaboration and re-compiling is already there (but not the caching, #47). 

> About LSP protocol vs having your own (like PureScript): I feel starting with a proprietary way of getting the information out of the compiler is the start. Implementing the actual protocol itself, possibly by adding a translation layer, is always possible and not really a priority atm (since there is nothing right now :D).

I'm with you on this. The reason I stopped working on this is when I realized that LSP is big and complex and I didn't want to get into _that_ rabbit hole only for the sake of having autocompletion in my Emacs. :-) In addition, my ELisp skills are seriously lacking!

> Anyway a bit of a braindump here, but I'd just like to see where you're at in this project, how we could get local bindings in, and if we could use the daemon or if that is just a bad way to go.

I didn't get too far, only wrote some code to output JSON.

As you can see, the function `dumpDecl` is of interest here. It doesn't inspect declarations much, though (which is why it only outputs the top-level declarations). So, to get the type of an identifier under cursor, you'd need to traverse the tree, looking for a variable which covers the cursor's location. Quite doable but probably inefficient.

I also started reading about what other similar projects are doing. I think it wasn't such a good idea after all, for there are so many ways to skin a cat.

**Comment by achlipala** [comment]
> In terms of autocompletion it would be great if we could use the same machinery to also get context-sensitive autocompletion (so including local bindings).

The type-inference daemon is only saving top-level module signatures, so no local bindings represented at all, let alone with types annotated.

**Comment by achlipala** [comment]
Well, I should clarify that elaborated terms are saved, but there is no crawling of program structure, beyond passing off to compiler phases.

**Comment by FrigoEU** [comment]
On a very high level, I'm thinking of having the daemon grab all of it's
cached top level bindings up unto the "current" top level binding, ie.
where the cursor is currently positioned. Then with that info run
elaboration on the current top level binding and use the resulting type
environment on the right "depth" for type-under-cursor and autocompletion.

Does that make any sense at all?

**Comment by achlipala** [comment]
I see two challenges with that approach.

First, there is no support for incremental retypechecking taking time proportional to the amount of code that has changed.  All dependencies of a changed module are rechecked -- not a good recipe for interactive-speed diagnostics.

Second, if we don't have fine-grained retypechecking, then the current file content might diverge from the content of the cached one, making it hard to match up structure and therefore get good guesses of identifier properties.

Pretty big changes to the type-inference approach would be required to support what you're asking for, IMO.  Or maybe you could detect when a change leaves the signature of a module intact and then cut off rechecking of depending modules.

**Comment by FrigoEU** [comment]
I'm slowly coming back to this and the first step would be to figure out what terms a cursor position in a file belongs to. I'd like to pass file + row num + col num to the compiler and it would tell me what term(s) are present on that position. I'd like to use the ModDb to get the elaboration results of the last pass for now (it will be fast and I think reasonably accurate, but it's just the first step) and then figure out what terms are on that position. The functions in Elab_util don't provide source spans however. Is my only option to add source spans to these functions (it's really hard to get my head around this mapfoldB stuff!) or is there another way to trace cursor position back through an Elab.decl structure?

**Comment by FrigoEU** [comment]
The outline of my current plan to handle "type at location":
Load up all identifiers from all the previous modules into an env from the daemon, even if there are type errors (right now the daemon doesn't cache those but it does on my fork). Then descend through the declaration that contains the cursor, again building up the environment more, and once we arrive at the cursor we look through the env for the requested identifier. It's not perfect to use the daemon, but it does have some advantages like speed, and some resilience in the event of errors... I'd like to just give it a try and see how it is in practice.

**Comment by FrigoEU** [comment]
I've made some good progress with this. I have a version that works like I described above. It took me some time to get it working, but I've been slowly getting familiar with the compiler codebase and I'm really really impressed with it's architecture. 

It's not polished at all and mostly falls back to printing Elab.decl, Elab.exp, Elab.con terms with ElabPrint functions, but I've already special cased a couple of them to look up names in the environment and it works great! It even works with local variables, let bindings, and "open" statements. It also works when you have errors in your project, since I modified the daemon to cache all results of the elaboration phase.

I'm really excited about this, and I'm pretty sure this could also be used for other tooling like autocomplete.

One thing that I haven't solved though, and really don't know how to go about, is the fact that you can't "interrupt" the daemon. I really often start compiling something, see mistakes coming up and want to recompile immediately. I always have to wait for the daemon to finish, which takes +- 40 seconds with the "-tc" flag. Also I'm using the daemon for this tooling stuff and that just makes this even worse. Probably would be a good idea to have the "tooling stuff" run in a seperate process but honestly I have no idea.

Now I'm just wondering if I should make a PR with this unfinished stuff so I can get feedback, or polish it slowly while I use it?

**Comment by ashalkhakov** [comment]
Definitely make a PR, if you think it's not up to standard just mark it WIP.

**Comment by FrigoEU** [comment]
FYI, my work on this has resulted in #186.

**Comment by ashalkhakov** [comment]
I'm closing this. I think that #186 is more than a suitable replacement. Thanks @FrigoEU!
