### ISSUE TITLE
Funny spacing in generated .sql files

### ISSUE THREAD

**Issue by mdempsky** [urweb/urweb#198]
It looks like the SQL printer is increasing the indentation level during `CREATE SEQUENCE` and `CREATE TABLE` statements, but then failing to reset it fully:

```
matthew@bento:~/wd/urweb/demo$ urweb chat
matthew@bento:~/wd/urweb/demo$ cat chat.sql; echo '<<EOF>>'
CREATE SEQUENCE uw_Chat_Room_s;
 
 CREATE TABLE uw_Chat_Room_t(uw_id int8 NOT NULL, uw_client int4 NOT NULL, 
                              uw_channel int8 NOT NULL,
  CONSTRAINT uw_Chat_Room_t_pkey PRIMARY KEY (uw_client, uw_id)
   
  );
  
  CREATE SEQUENCE uw_Chat_s;
   
   CREATE TABLE uw_Chat_t(uw_id int8 NOT NULL, uw_title text NOT NULL, 
                           uw_room int8 NOT NULL,
    CONSTRAINT uw_Chat_t_pkey PRIMARY KEY (uw_id)
     
    );
    
    <<EOF>>
```

**Comment by ashalkhakov** [comment]
Can confirm, it's also the case with all pretty-printed code coming out Ur/Web. I stumbled upon this when working on a pretty-printer for Ur/Web source code.

**Comment by achlipala** [comment]
Right, I've been aware of this unpleasant behavior since the earliest days of Ur/Web.  Since everything remains fine from a semantic perspective, I didn't invest enough effort to fix it yet, but I'm sure there's a good way, and I'd very much welcome a PR fixing use of the SML/NJ pretty-printing library to this end!

**Comment by mdempsky** [comment]
Spent some time learning about the SML/NJ pretty printing library ("PP") last night.

As far as I can tell, the closest thing to official docs are the comments here: https://github.com/sml-nj/smlnj/blob/master/smlnj-lib/PP/src/pp-stream-sig.sml

OCaml has some more detailed description of its pretty printing library, which seems similar (maybe the same?): https://ocaml.org/learn/tutorials/format.html

My impression is the PP library works best when spacing is used between box elements, whereas cjr_print.sml's DDL printing code uses newlines at the end of boxes. In particular, this is what causes the indentation to keep accumulating across each box.

**Comment by achlipala** [comment]
Ah, nice find!  Consider this queued up for me to look into some week soon, though I'd also be quite glad to see a PR that moves newlines out of boxes (if it has the expected effect).

**Comment by ashalkhakov** [comment]
I have tried to fix this over the weekend. Still wrapping my head trying to think of *two* cases at once when writing pretty-printing code: when there is enough space on the line, and when we have to break lines.

What I found is that Ur/Web is basically outputting text paragraphs all the way (via the `box`), that's why it's so funny looking. :) However, just taking newlines out of boxes doesn't help much, unfortunately.

There is also the issue of indentation:

* the `Abs` indentation is actually *relative to the parent box*
* the `Rel` indentation is *relative to the sibling box*

Ur/Web always uses `Rel` IIRC.

**Comment by achlipala** [comment]
Hm, so do you think it could be as simple as changing the very few occurrences of `Rel` to `Abs`?

**Comment by ashalkhakov** [comment]
@achlipala Let me try that. It might work :)

**Comment by ashalkhakov** [comment]
@achlipala Yep it works better! Should I do a PR?

**Comment by achlipala** [comment]
Please do.  Thanks.

**Comment by ashalkhakov** [comment]
It fixes MOST of the issues with C output as well; although it still needs a bit of adjustment.
