### ISSUE TITLE
"Iflow: not ready for joins or nesteds"

### ISSUE THREAD

**Issue by AlexanderAA** [urweb/urweb#24]
How difficult would it be to add joins and nesteds support into Iflow (and, maybe, some simpler cases of signal)? Are there any existing notes/papers on how that should work?

**Comment by achlipala** [comment]
Probably not too hard!  Have you seen [the paper on this analysis](http://adam.chlipala.net/papers/UrFlowOSDI10/)?

Warning: even what's already implemented is very much research-prototype level and not production-ready.  It hasn't had any real attention paid to it since 2010.  I would love for someone to take charge of making it "real," but it hasn't been a priority for anyone yet.

So I'll close this issue for now; though it would be great if you wanted to contribute patches broadening the scope of the analysis, most likely that would require a lot of guidance from me, which I don't have the time to give now.

**Comment by vizziv** [comment]
Possibly relevant: the functions in `Sqlcache.FlattenQuery` transform a nested query into a list of simple queries without unions or joins. I don't know how Iflow works, but commenting here in case this existing code makes a fix easy for some future reader.
