### ISSUE TITLE
urweb-mode: font-lock-cvariable-face hard-coded to "dark blue"

### ISSUE THREAD

**Issue by tuncer** [urweb/urweb#46]
font-lock-cvariable-face is hard-coded to "dark blue", and this breaks visibility in some themes. It should probably reuse a well-known face, but I don't know which.

**Comment by cpitclaudel** [comment]
`font-lock-type-face` doesn't seem to be used anywhere in the current urweb-mode, so maybe that? For better customizability `font-lock-cvariable-face` could be customized to inherit from it.

Otherwise, the face definition could easily be altered to be different on dark and light themes. Here's an example from `tuareg-mode`:

```
(defface tuareg-font-lock-interactive-output-face
  '((((background light))
     (:foreground "blue4"))
    (t (:foreground "grey")))
  "Face description for all toplevel outputs."
  :group 'tuareg-faces)
```

By the way, urweb-mode seems to define a bunch of non-standard faced in the font-lock namespace (the one discussed here, plus `font-lock-type-def-face`, `font-lock-module-def-face`, and others). This isn't the best: urweb definitions should start with `urweb-`; it can cause clashes with other modes that do the same incorrect thing, such as sml-mode (which I guess is where this pattern came from)

**Comment by tuncer** [comment]
I'm by no means an Emacs expert, so I would appreciate it if you want to submit a patch.

**Comment by achlipala** [comment]
OK, I've implemented Clement's suggestion.
