### ISSUE TITLE
MonoReduce is too careful about impurity

### ISSUE THREAD

**Issue by vizziv** [urweb/urweb#7]
I'm getting an error compiling the Examples/Resistance/resistance project in [this repo](https://github.com/vizziv/UrLib/), and Cjrize fails because there's an anonymous function. The context around the function is [here](https://github.com/vizziv/UrLib/blob/master/Examples/Resistance/problem.mono), where the offending function is the innermost `fn {} => ...`.

There's a case in MonoReduce that I'm pretty sure is supposed to commute the relevant `ELet` and `EAbs` if possible, but it's only sure to commute them if the bound expression in `ELet` is pure. MonoReduce's `impure` returns `true` for any non-FFI `EApp`. Modifying the check to consider any application of a named variable beginning with "urlify" alleviates the aforementioned error, but obviously that's not the right fix.

I think Sqlcache's `effectful` does a more precise impurity check, but it needs to be run several times to determine which named variables are impure, Bellman-Ford style. I might have a go at making a patch tomorrow or later this week.

(Solving this first anonymous function error with the "urlify" kludge reveals more anonymous function errors in another module. I think they're all caused by a `transaction` inside an `option` or `variant`.)

For completeness, the entire Mono output from the phase before Cjrize is [here](https://github.com/vizziv/UrLib/blob/master/Examples/Resistance/resistance.mono).

**Comment by achlipala** [comment]
I agree that it would be perfectly reasonable, and probably generally useful, to make MonoReduce's purity analysis more precise, by doing some call-graph analysis to determine which named functions are actually pure.  I don't think anything so complex as Bellman-Ford is likely to be necessary.  The reason is that the Unnest optimizations break up mutually recursive definitions, and afterward it's usually sufficient to consider a whole set of mutually recursive definitions as one recursive definition, which is impure iff it does something impure directly or calls a previously defined impure function.  That is, it works fine to step through all module-level declarations in order, with no fixed-point calculation.

If you're willing to take a shot at implementing this analysis improvement, I'll appreciate it!

**Comment by vizziv** [comment]
Okay, I'll have something soon.

**Comment by vizziv** [comment]
Evidently I did not have something soon, mostly because the this hasn't come up again enough for it to be a problem.
