### ISSUE TITLE
Missing linker flag with clang in Linux

### ISSUE THREAD

**Issue by achlipala** [urweb/urweb#8]
`configure.ac` includes some code to check for clang and, if found, remove all linker arguments to select pthreads libraries.  Leaving those arguments in there definitely made trouble on OS X in the past.  However, I'm now noticing that they do need to be present with clang on Linux.

@JasonGross, @bbarenblat, @vizziv, other wizards who have helped with such things in the past: do you know what is actually the right thing to be doing in `configure.ac`?

**Comment by JasonGross** [comment]
Removing the custom code results in a warning (though not an error) on clang on Mac OS.  It seems like this is [a bug in older versions of `AX_PTHREAD`](http://savannah.gnu.org/patch/?8186).  I think the right solution is to upgrade the version of `m4/m4_ax_pthread.m4` that we ship to [the latest version](http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=blob_plain;f=m4/ax_pthread.m4), and then remove the custom code in `configure.ac`.

**Comment by achlipala** [comment]
Thanks.  That seems to do it.

**Comment by vizziv** [comment]
On my OS X machine, after this fix, Ur/Web itself builds without error, but when running the compiler itself, the last stage of the Ur/Web compiler fails with `clang: error: argument unused during compilation: '-pthread'`.

Apparently, clang on darwin needs -pthread to be passed when compiling but not when linking. Because of `-Werror`, the unused argument warning becomes an error.

As a workaround, I added `-Qunused-arguments` to `CCARGS` before configuring, but perhaps some m4 magic can help....

**Comment by JasonGross** [comment]
I think the Right Thing to do would be to figure out what `m4` magic needs to happen to discover this behavior.  @vizziv, this is probably going to be easier for you to do than for me, since I have to wait two minutes to test every change I make via travis, since I have no mac.  I think what you want to do is modify `m4/m4_ax_pthread.m4`, by adding something after
```m4
        AC_LINK_IFELSE([AC_LANG_PROGRAM([#include <pthread.h>
                        static void routine(void *a) { a = 0; }
                        static void *start_routine(void *a) { return a; }],
                       [pthread_t th; pthread_attr_t attr;
                        pthread_create(&th, 0, start_routine, 0);
                        pthread_join(th, 0);
                        pthread_attr_init(&attr);
                        pthread_cleanup_push(routine, 0);
                        pthread_cleanup_pop(0) /* ; */])],
                [ax_pthread_ok=yes],
                [])
```
to do something like
```m4
        AC_some-magic_IFELSE(some arguments to build and link and test a program that will fail on Darwin with -pthread,
                [],
                [ax_pthread_ok=no])
```

If you can find the conditions that make a program fail (is it compiling a program that makes no use of pthreads with `-pthread`? is it linking *any* program with `-pthread`?  is it linking programs that don't use pthreads with `-pthread`?  is it linking, with `-pthread`, programs compiled without `-pthread`?  something else?), I can try my hand at writing the `m4` magic.  And then we should submit a bug report and patch to upstream autotools...

**Comment by eranmeir** [comment]
Apparently the compiler used the pthread cflags for the linker as well. Pull request in #10 fixes it

**Comment by JasonGross** [comment]
I've asked [a question on stackoverflow](http://stackoverflow.com/questions/34562297/variant-of-ac-link-ifelse-that-does-compilation-and-linking-separately-in-config) about the needed m4 magic.

**Comment by achlipala** [comment]
Surprisingly given that Travis is happy, here's what I get now running `make test` on my Ubuntu 14.04 laptop:
```
$ bin/urweb -debug -boot -noEmacs -dbms sqlite -db /tmp/urweb.db -demo /Demo demo
gcc  -pthread -Wimplicit -Werror -Wno-unused-value -I /home/adamc/git/urweb/include/urweb  -c "/tmp/webapp.c" -o "/tmp/webapp.o" -g
gcc -Werror   "/tmp/webapp.o" /home/adamc/git/urweb/src/c/.libs/liburweb_http.a /home/adamc/git/urweb/src/c/.libs/liburweb.a -lm -lcrypto -lssl -lsqlite3 -o "/home/adamc/git/urweb/demo/demo.exe" -g
/usr/bin/ld: /home/adamc/git/urweb/src/c/.libs/liburweb.a(urweb.o): undefined reference to symbol 'pthread_rwlock_wrlock@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

Any idea what's going on?  (@eranmeir?)

**Comment by JasonGross** [comment]
Can you save the temporaries, and see if adding `-lpthread` to that second `gcc` line fixes it?

I'm starting to suspect that we need `-lpthread` for both compilation and linking on linux, and we need the absence of `-lpthread` for linking on mac (and it doesn't matter for compilation).

**Comment by achlipala** [comment]
Yes, I already verified that passing `-pthread` in the linker line fixes the problem.  Your diagnosis sounds accurate, and we really just want the M4 macros to set variables accordingly.

**Comment by achlipala** [comment]
OK, I think I've fixed this now.  @vizziv, can you confirm that everything is hunky-dory on your personal Mac, with no need for extra flags?

The most important insight was that the M4 macros had a special case for Darwin, but removing it leaves everything working fine!  The special case was testing `-pthread` before other ways of making Pthreads work, including before trying no arguments at all (the right choice for current OS X).  Somehow the testing logic was accepting an option that doesn't actually work, the way `urweb` uses it.  A mystery to solve another time.

I think I'll put out a new Ur/Web release soon, if we can confirm that this change is good for everyone.

**Comment by vizziv** [comment]
Yep, it works!

**Comment by JasonGross** [comment]
[Response from the autoconf mailing list](https://lists.gnu.org/archive/html/autoconf-archive-maintainers/2016-01/msg00005.html):
> 
From:	Daniel Richard G.
Subject:	Re: AX_PTHREAD incorrectly adds -pthread on OSX
Date:	Fri, 22 Jan 2016 20:30:43 -0500
Hi Peter,
>
Spurred by your/this e-mail, I've started working on this macro again to
finally get a working version pushed out.
>
On Fri, 2016 Jan  8 19:56+0100, Peter Simons wrote:
> > I'm forwarding this message to Steven and Richard, the macro's
> authors.
> >
> Peter
> >
> > Jason Gross <address@hidden> writes:
>
Hi Jason, sorry for the wait. Lot of loose threads from the holiday!
>
> > > The latest version of AX_PTHREAD
> > (dd946914edb9da25e2d8c8b2186fab5d8103f3d4, serial 21) does not work
> > on OS X. It tests for whether or not `clang -o conftest -g -O2
> > -pthread -Werror conftest.c` succeeds (which it does), when it
> > actually needs to be checking for `clang -o conftest.o -g -O2
> > -pthread -Werror - c conftest.c && clang -o conftest -g -O2 -pthread
> > -Werror conftest.o` (which, I believe, fails). If there's a variant
> > of AC_LINK_IFELSE that does the compilation separately from the
> > linking, then the change should be as simple as
>
AC_LINK_IFELSE() is defined at the Autoconf level. I can't change how it
works, and there isn't any alternative macro that performs the link
separately from the compilation. Even if there were, it wouldn't solve
the problem.
>
The issue is that [certain older versions of] Clang takes -pthread when
compiling, but doesn't want the flag when it is only linking. This flies
in the face of how basically every other C compiler works, where compile-
time flags are at least silently ignored when linking with the compiler
frontend, and are at times actually required (e.g. flags indicating 64-
bit mode) in order for the link to succeed.
>
That is why Automake always includes $(CFLAGS) when linking with
$(CC), in addition to $(LDFLAGS). If you want to have a flag that is
used *only* at compile time, that's actually a bit tricky to pull off
[with Automake].
>
What's more, not setting PTHREAD_CFLAGS="-pthread" is actually an
incorrect result, because then _REENTRANT is not #defined, meaning
that "errno" and the like are not defined appropriately for multi-
threaded builds.
>
Ultimately, it is not possible to build POSIX-threaded software with
this combination of elements:
>
1. A version of Clang that complains about -pthread when only linking
>
2. Automake
>
3. -pthread
>
4. -Werror
>
One of those has to be taken out. Removing #1 or #2 tends not to be
practically feasible. #3 is required for correct compilation. So it's #4
that's got to go. Sometimes, you just can't avoid a warning.
>
> > > plus associated documentation and indentation changes, but I don't
> > know if anything like AC_COMPILE_AND_LINK_SEPARATELY_IFELSE exists----
> > does it?
>
Not in Autoconf proper. There's never been a need for it, and the
Clang folks have corrected the behavior of the -pthread flag in more
recent versions.
>
>
--Daniel
>
>
-- 
Daniel Richard G. || address@hidden
My ASCII-art .sig got a bad case of Times New Roman.

**Comment by achlipala** [comment]
OK, sounds like my fix was probably right, then.
