### ISSUE TITLE
/etc/mime.types does not exists on macOS Sierra, v 10.12.

### ISSUE THREAD

**Issue by peterbb** [urweb/urweb#89]
Compiling  a project which has `file style.css style.css` in the project description gives the following warning on my system: 
 
    WARNING: Error opening /etc/mime.types.  Static files will be served with no suggested MIME types.

As the warning correctly notes, there is no file `/etc/mime.types` on my system, which consists of:

* macOS Sierra, version 10.12
* urweb version 20170720

I'm not familiar enough with the implications of this warning, and if this is a problem, but it seems to me that two possible solutions are:

* Somehow make it possible to point to an alternative location for the mime.types file. For instance `mimeTypes <path>` as a directive in project files, or as an argument to the `urweb` executable.
* Allow the `file` directive to take an optional last argument, specifying the mime-type. E.g. `file <path> <path> <mime-type>`. In my example I would then write `file type.css style.css text/css`.

**Comment by achlipala** [comment]
The implications of the warning are that browsers accessing the file won't receive guidance from the web server on what type of file it is.  They can still use the file extension as a hint, of course.

Both of your suggestions sound reasonable, and I'd be glad to have both of them implemented in Ur/Web.  If you submit a PR with these features, I can accept it shortly.  Otherwise, this goes on my to-do list, to implement in the medium term.

**Comment by achlipala** [comment]
OK, directives added in the latest commit.

**Comment by k4rtik** [comment]
Commit referenced above: https://github.com/urweb/urweb/commit/b1a6440a3fb285cdfd5301510b96b1ef3b96c050
